name: barcode_scan2
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 4.0.0+3
homepage: https://github.com/mono0926/barcode_scan2

dependencies:
  protobuf: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: BarcodeScanPlugin
